type IsoCurrency = {
  code: string;
  symbol: string;
  decimals?: number;
};

/**
 * Circulating ISO 4217 currencies used for symbol/decimal formatting.
 * Keep in sync with mobile/utils/isoCurrencies.ts.
 */
const ISO_CURRENCIES: IsoCurrency[] = [
  { code: "AED", symbol: "AED" },
  { code: "AFN", symbol: "؋" },
  { code: "ALL", symbol: "L" },
  { code: "AMD", symbol: "֏" },
  { code: "ANG", symbol: "ƒ" },
  { code: "AOA", symbol: "Kz" },
  { code: "ARS", symbol: "AR$" },
  { code: "AUD", symbol: "A$" },
  { code: "AWG", symbol: "ƒ" },
  { code: "AZN", symbol: "₼" },
  { code: "BAM", symbol: "KM" },
  { code: "BBD", symbol: "Bds$" },
  { code: "BDT", symbol: "৳" },
  { code: "BGN", symbol: "лв" },
  { code: "BHD", symbol: "BD" },
  { code: "BIF", symbol: "FBu", decimals: 0 },
  { code: "BMD", symbol: "BD$" },
  { code: "BND", symbol: "B$" },
  { code: "BOB", symbol: "Bs" },
  { code: "BRL", symbol: "R$" },
  { code: "BSD", symbol: "B$" },
  { code: "BTN", symbol: "Nu" },
  { code: "BWP", symbol: "P" },
  { code: "BYN", symbol: "Br" },
  { code: "BZD", symbol: "BZ$" },
  { code: "CAD", symbol: "C$" },
  { code: "CDF", symbol: "FC" },
  { code: "CHF", symbol: "CHF" },
  { code: "CLP", symbol: "CL$", decimals: 0 },
  { code: "CNY", symbol: "¥" },
  { code: "COP", symbol: "CO$" },
  { code: "CRC", symbol: "₡" },
  { code: "CUP", symbol: "CU$" },
  { code: "CVE", symbol: "CVE" },
  { code: "CZK", symbol: "Kč" },
  { code: "DJF", symbol: "Fdj", decimals: 0 },
  { code: "DKK", symbol: "kr" },
  { code: "DOP", symbol: "RD$" },
  { code: "DZD", symbol: "DA" },
  { code: "EGP", symbol: "E£" },
  { code: "ERN", symbol: "Nfk" },
  { code: "ETB", symbol: "Br" },
  { code: "EUR", symbol: "€" },
  { code: "FJD", symbol: "FJ$" },
  { code: "FKP", symbol: "£" },
  { code: "GBP", symbol: "£" },
  { code: "GEL", symbol: "₾" },
  { code: "GHS", symbol: "₵" },
  { code: "GIP", symbol: "£" },
  { code: "GMD", symbol: "D" },
  { code: "GNF", symbol: "FG", decimals: 0 },
  { code: "GTQ", symbol: "Q" },
  { code: "GYD", symbol: "G$" },
  { code: "HKD", symbol: "HK$" },
  { code: "HNL", symbol: "L" },
  { code: "HTG", symbol: "G" },
  { code: "HUF", symbol: "Ft" },
  { code: "IDR", symbol: "Rp" },
  { code: "ILS", symbol: "₪" },
  { code: "INR", symbol: "₹" },
  { code: "IQD", symbol: "IQD" },
  { code: "IRR", symbol: "IRR" },
  { code: "ISK", symbol: "kr", decimals: 0 },
  { code: "JMD", symbol: "J$" },
  { code: "JOD", symbol: "JD" },
  { code: "JPY", symbol: "¥", decimals: 0 },
  { code: "KES", symbol: "KSh" },
  { code: "KGS", symbol: "сом" },
  { code: "KHR", symbol: "៛" },
  { code: "KMF", symbol: "CF", decimals: 0 },
  { code: "KRW", symbol: "₩", decimals: 0 },
  { code: "KWD", symbol: "KD" },
  { code: "KYD", symbol: "CI$" },
  { code: "KZT", symbol: "₸" },
  { code: "LAK", symbol: "₭" },
  { code: "LBP", symbol: "LBP" },
  { code: "LKR", symbol: "Rs" },
  { code: "LRD", symbol: "L$" },
  { code: "LSL", symbol: "L" },
  { code: "LYD", symbol: "LD" },
  { code: "MAD", symbol: "DH" },
  { code: "MDL", symbol: "L" },
  { code: "MGA", symbol: "Ar" },
  { code: "MKD", symbol: "ден" },
  { code: "MMK", symbol: "K" },
  { code: "MNT", symbol: "₮" },
  { code: "MOP", symbol: "MOP$" },
  { code: "MRU", symbol: "UM" },
  { code: "MUR", symbol: "₨" },
  { code: "MVR", symbol: "Rf" },
  { code: "MWK", symbol: "MK" },
  { code: "MXN", symbol: "MX$" },
  { code: "MYR", symbol: "RM" },
  { code: "MZN", symbol: "MT" },
  { code: "NAD", symbol: "N$" },
  { code: "NGN", symbol: "₦" },
  { code: "NIO", symbol: "C$" },
  { code: "NOK", symbol: "kr" },
  { code: "NPR", symbol: "रू" },
  { code: "NZD", symbol: "NZ$" },
  { code: "OMR", symbol: "OMR" },
  { code: "PAB", symbol: "B/." },
  { code: "PEN", symbol: "S/" },
  { code: "PGK", symbol: "K" },
  { code: "PHP", symbol: "₱" },
  { code: "PKR", symbol: "₨" },
  { code: "PLN", symbol: "zł" },
  { code: "PYG", symbol: "₲", decimals: 0 },
  { code: "QAR", symbol: "QAR" },
  { code: "RON", symbol: "lei" },
  { code: "RSD", symbol: "din" },
  { code: "RUB", symbol: "₽" },
  { code: "RWF", symbol: "FRw", decimals: 0 },
  { code: "SAR", symbol: "SAR" },
  { code: "SBD", symbol: "SI$" },
  { code: "SCR", symbol: "₨" },
  { code: "SDG", symbol: "SDG" },
  { code: "SEK", symbol: "kr" },
  { code: "SGD", symbol: "S$" },
  { code: "SHP", symbol: "£" },
  { code: "SLE", symbol: "Le" },
  { code: "SOS", symbol: "Sh" },
  { code: "SRD", symbol: "Sr$" },
  { code: "SSP", symbol: "£" },
  { code: "STN", symbol: "Db" },
  { code: "SYP", symbol: "£" },
  { code: "SZL", symbol: "L" },
  { code: "THB", symbol: "฿" },
  { code: "TJS", symbol: "SM" },
  { code: "TMT", symbol: "m" },
  { code: "TND", symbol: "DT" },
  { code: "TOP", symbol: "T$" },
  { code: "TRY", symbol: "₺" },
  { code: "TTD", symbol: "TT$" },
  { code: "TWD", symbol: "NT$" },
  { code: "TZS", symbol: "TSh" },
  { code: "UAH", symbol: "₴" },
  { code: "UGX", symbol: "USh", decimals: 0 },
  { code: "USD", symbol: "$" },
  { code: "UYU", symbol: "$U" },
  { code: "UZS", symbol: "so'm" },
  { code: "VES", symbol: "Bs" },
  { code: "VND", symbol: "₫", decimals: 0 },
  { code: "VUV", symbol: "VT", decimals: 0 },
  { code: "WST", symbol: "T" },
  { code: "XAF", symbol: "FCFA", decimals: 0 },
  { code: "XCD", symbol: "EC$" },
  { code: "XOF", symbol: "CFA", decimals: 0 },
  { code: "XPF", symbol: "₣", decimals: 0 },
  { code: "YER", symbol: "YER" },
  { code: "ZAR", symbol: "R" },
  { code: "ZMW", symbol: "ZK" },
  { code: "ZWG", symbol: "ZiG" },
];

export const CURRENCY_SYMBOLS: Record<string, string> = Object.fromEntries(
  ISO_CURRENCIES.map((currency) => [currency.code, currency.symbol])
);

export const ZERO_DECIMAL_CURRENCIES = new Set(
  ISO_CURRENCIES.filter((currency) => currency.decimals === 0).map((currency) => currency.code)
);

const ISO_CURRENCY_SET = new Set(ISO_CURRENCIES.map((currency) => currency.code));

export function normalizeIsoCurrency(code: unknown): string | null {
  if (typeof code !== "string") return null;
  const normalized = code.trim().toUpperCase();
  return ISO_CURRENCY_SET.has(normalized) ? normalized : null;
}

export function isValidIsoCurrency(code: unknown): code is string {
  return normalizeIsoCurrency(code) !== null;
}
